/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as CallTokenRouteImport } from './routes/call/$token'
import { Route as AppCashRouteImport } from './routes/app/cash'
import { Route as AppAgentsRouteImport } from './routes/app/agents'
import { Route as AppActionsRouteImport } from './routes/app/actions'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const CallTokenRoute = CallTokenRouteImport.update({
  id: '/call/$token',
  path: '/call/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cash': typeof AppCashRoute
  '/call/$token': typeof CallTokenRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/actions': typeof AppActionsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cash': typeof AppCashRoute
  '/call/$token': typeof CallTokenRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/actions': typeof AppActionsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/cash': typeof AppCashRoute
  '/call/$token': typeof CallTokenRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/agents'
    | '/app/cash'
    | '/call/$token'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/app/actions' | '/app/agents' | '/app/cash' | '/call/$token' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/actions'
    | '/app/agents'
    | '/app/cash'
    | '/call/$token'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CallTokenRoute: typeof CallTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/call/$token': {
      id: '/call/$token'
      path: '/call/$token'
      fullPath: '/call/$token'
      preLoaderRoute: typeof CallTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cash': {
      id: '/app/cash'
      path: '/cash'
      fullPath: '/app/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppCashRoute: typeof AppCashRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppCashRoute: AppCashRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CallTokenRoute: CallTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
